### ISSUE TITLE
Genre

### ISSUE THREAD

**Issue by maboroshin** [stephane-r/holoplay-pwa#13]
Is it okay if I requesting more features? 

It would be useful to easily select a genre. It would just pass the genre word on to the search term.

Sample is my tool : https://genkaku.in/tool/. Or Hyperpipe ( Youtube Music client) https://hyperpipe.surge.sh/explore/. Or Beatbump (Same) https://beatbump.io/trending. There will be more: Metal Indie pop folk instrumental british german.

**Comment by stephane-r** [comment]
Yes, i like the idea.

How do you see the thing ? A static gender list, on click you launch a simple search ? (e.g. https://invidious.projectsegfau.lt/api/v1/search?q=rap) ?

**Comment by maboroshin** [comment]
That method will be fine. Retrieve by music genre from YouTube. No other apps do this yet, maybe.

Youtube Music seems to have a genre. YouTube Music clients seems to get this. The Spotify client SpoTube seems to use Spotify genres. Nuclear is taken tracks/artists from Last.fm. https://www.last.fm/music

**Comment by stephane-r** [comment]
Ok.

For now, i think add static genre list 👍

**Comment by stephane-r** [comment]
Hey @maboroshin 

I've add genre list in dashboard : 

![image](https://github.com/stephane-r/holoplay-pwa/assets/4712791/f3f3aea1-0426-4d68-a4e2-94a18ede5ed1)

I've use this basic spotify genre list : https://gist.github.com/drumnation/91a789da6f17f2ee20db8f55382b6653

On genre press, it run simple invidious search with genre query. Maybe the style need to be rework.

Available on 1.9.0 version

**Comment by maboroshin** [comment]
@stephane-r Nice work!
