### ISSUE TITLE
Volume resetting when loading other page

### ISSUE THREAD

**Issue by melliiii** [stephane-r/holoplay-pwa#21]
Hey there!
Really like your project. i installed it through CasaOS in a docker container (spout8301/holoplay:1.9.1) and the volume keeps resetting to max when i play a song and for example switch to playlists or even change the song.

Im running Firefox Version 117.0 (64bit), Edge 116.0.1938.69 (64bit) and Chrome 116.0.5845.180 (64bit). 
Neither Chrome or Edge got Extentions installed.

In Edge the Audio Mode isnt supported sometimes (youtube unknown error 150) and then again it works after reloading.

My Setup:
Proxmox Container running debian11-standard_11.7, CasaOS v0.4.4.2 and docker version 24.0.6 (build ed223bc)

[My docker config file spat out by Portainer](https://hastebin.skyra.pw/pusihozasu.json)

Steps to reproduce:
1. Install Docker Container spout8301/holoplay:1.9.1
2. go to IP_ADDR:3000
3. change to darkmode
4. Search for a song in the search bar (in my example "This Suffering" by Billy Talent, love that song!)
5. Change volume
6. click on playlists on the sidebar

This should reset the volume back to max.

If you have any questions please dont hesitate to contact me :)
~ Melli

**Comment by stephane-r** [comment]
Hi @melliiii 😃 

Thank you for your report, I also reproduce your usecase. A publish version is planned for next week, I will take the opportunity to add the fix.

Thank you for your very detailed issue 👍

**Comment by stephane-r** [comment]
Fixed in https://github.com/stephane-r/holoplay-pwa/commit/8fb92ed93d137c6da63097291b8ec335c1041089

Added in next release.

**Comment by stephane-r** [comment]
Published on 1.9.2.
