### ISSUE TITLE
SponsorBlock

### ISSUE THREAD

**Issue by maboroshin** [stephane-r/holoplay-pwa#3]
If this app gets Youtube and plays music, it would be nice if SponsorBlock could be used.

**Comment by stephane-r** [comment]
I'm not really understand what the SponsorBlock would be ?

**Comment by maboroshin** [comment]
I didn't explain it well.

https://github.com/ajayyy/SponsorBlock
SponsorBlock is a project to detect irrelevant segments in YouTube videos.

Extensions: https://sponsor.ajay.app/
Peoples will install browser extensions. They submit segments that are not related to the subject matter in the video. The database is shared. The more viewed videos will be in the database.

Category guideline: https://wiki.sponsor.ajay.app/w/Guidelines
These segments are labeled with various labels as prescribed.

https://youtu.be/w4cTYnOPdNk
This video has non-music intro/outro segments. Especially if these segments are talk show style, we will be perceived as not music. 

https://piped.video/watch?v=w4cTYnOPdNk
Piped and Nuclear(Software) skip this segments. This will be especially important for listening to music.

**Comment by stephane-r** [comment]
Hello @maboroshin 

I've add preview on #12 PR and with this preview env : https://holoplay-pwa-git-sponsor-block-stephane-r.vercel.app/search?q=w4cTYnOPdNk&type=video&sortBy=relevance&time=all&duration=all&service=invidious

**Comment by maboroshin** [comment]
@stephane-r Nice! It seems to be no problem.

* This instantly skipped the 40 second intro in "Super Shy". https://holoplay-pwa-git-sponsor-block-stephane-r.vercel.app/search?q=ArmDp-zijuc
* Multiple scenes in this video will also be skipped. https://holoplay-pwa-git-sponsor-block-stephane-r.vercel.app/search?q=XIOoqJyx8E4

**Comment by maboroshin** [comment]
Difficult to distinguish before playback in light mode.
![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/c19e4804-8d33-40bd-ae49-42afa9eb4d44)

After playing Sponsor Scene.
![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/1311f1dd-2564-4843-962d-be753ac1ae00)

**Comment by stephane-r** [comment]
Thank you ! 

Agree for playback in light mode, i'll update before deploy in production :)
