### ISSUE TITLE
[Hacktoberfest] Translation string with English remaining

### ISSUE THREAD

**Issue by maboroshin** [stephane-r/holoplay-pwa#30]
```menu.video.other```: This "Other" remains in English.
![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/23cdb5bc-b91d-4677-9d0e-101e06d5960d)

Add Invidious Instance Dialog: ```settings.general.invidious.type``` can be used
![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/9cc65d60-4404-4a71-8276-eb6e3c6e6a5d)

**Comment by stephane-r** [comment]
Thank you for report, fixed on next release.
