### ISSUE TITLE
Start current playback on another HoloPlay device

### ISSUE THREAD

**Issue by stephane-r** [stephane-r/holoplay-pwa#32]
Similar to Spotify, being able to start current playback on another HoloPlay device.

Several possible approaches:

- use a user account and authenticate on both devices to have synchronization (requires a web server with a database)
- a simple websocket connection with a deviceId (requires a web server)
- a simple ping using the serverless function (link holoplay-serverless), the least practical method
- using WebRTC Messages

I would like to avoid the database approach : let's keep our data with us and not on some instance. The websocket approach is simple and suitable for functionality, but requires hosting a Node.js server.

Another method ?

**Comment by zlElo** [comment]
Which option was chosen?

**Comment by stephane-r** [comment]
Hello @zlElo 

I recently tested solutions 1 and 2 by migrating the CRA app to Next.js to benefit from an “included” server and not change the hosting.

This requires too much tweaking with server components, which is an approach HoloPlay doesn't need. We're adding too much complexity for not much.

I think solution 3 is the most pragmatic 👍 

Concerning the WebRTC approach, after reflection, this approach is perhaps not a good idea after all.

**Comment by stephane-r** [comment]
#81
