### ISSUE TITLE
CSS for mobile device

### ISSUE THREAD

**Issue by maboroshin** [stephane-r/holoplay-pwa#47]
The menu bar at the bottom will not appear until you scroll to the bottom. So, they are not displayed when additional content are loaded, such as search results.

![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/d487480c-213b-4f0c-bd37-32aa4faf0eca)

----

There is a blank space between the mini-player and the menu. The content can be displayed larger without this space.

![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/01ee522d-8a48-406e-ba80-fe8c1039c46e)

----

When the mini-player is enlarged, the close button is not visible on the small screen. Press the Back button on your browser to fit the screen. The close button will be available.

Tablets with wider screens don't have this problem.

![image](https://github.com/stephane-r/holoplay-pwa/assets/41102508/1498ddfe-f431-46e8-ba23-fe76c7a81fe3)

**Comment by stephane-r** [comment]
Hey @maboroshin 


I see the screenshots are on safari mobile? I'll do some testing and tweak it 😄

**Comment by maboroshin** [comment]
@stephane-r
Yes! These screenshots are from iPhone Safari.

I get the same problem with Chrome on iPhone and Android. FireFox on iPhone didn't have these problems.

Other browsers on Android have not been tested.

**Comment by stephane-r** [comment]
Hi @maboroshin 

Can you try the fix on branch preview environment ? https://github.com/stephane-r/holoplay-pwa/pull/53

Thank you !

**Comment by maboroshin** [comment]
@stephane-r
These are fixed on Android tablets.

On iOS it is fixed on first access. However I use search, Then the problem occurs again.

**Comment by stephane-r** [comment]
> @stephane-r These are fixed on Android tablets.
> 
> On iOS it is fixed on first access. However I use search, Then the problem occurs again.

Nice for Android. About iOS on search, is it the "auto zoom" on focused input ?

**Comment by stephane-r** [comment]
@maboroshin Pushing new update on preview environment :)

Thanky you !

**Comment by maboroshin** [comment]
@stephane-r All problems seem to have been fixed! Nice!

There's also a new little problem. Search with mini-player displayed. The navigation bar at the bottom will then be hidden. But this can be displayed by drag-drop with a tap.

**Comment by stephane-r** [comment]
Mmm yes it's okay now, it was the safari zoom on text input.

**Comment by maboroshin** [comment]
I understand. If it is ok, please close. Thank you.
