### ISSUE TITLE
docker: Error response from daemon: manifest for spout8301/holoplay:latest not found: manifest unknown: manifest unknown.

### ISSUE THREAD

**Issue by SerhatGulasti** [stephane-r/holoplay-pwa#83]
Hi,

When I try to pull or build the Docker image, I got the "
Unable to find image 'spout8301/holoplay:latest' locally
docker: Error response from daemon: manifest for spout8301/holoplay:latest not found: manifest unknown: manifest unknown." error.

Could you help me, please?

**Comment by stephane-r** [comment]
Hey @SerhatGulasti 

Try to pull the latest tag : 1.12.0 (spout8301/holoplay:1.12.0)

**Comment by SerhatGulasti** [comment]
It worked! 
Thanks.
