### ISSUE TITLE
Music player does not work on iOS

### ISSUE THREAD

**Issue by Caobita9** [stephane-r/holoplay-pwa#84]
I have installed HoloPlay on my server and when I access through my iOS device, the music does not play.

I have tried Safari and Edge, neither works, I think all browsers on iOS work under Web-Kit, maybe that is the problem, but I read that HoloPlay was compatible with iOS devices.

Can you please confirm this for me?

Also, I take advantage of this thread to ask something, is it normal that the thumbnails take a long time to load? Sometimes they don't even load, sometimes they load very fast and sometimes they load slowly.

Thank you for your help.

**Comment by stephane-r** [comment]
Hi @Caobita9 

I don't have an iPhone, but HoloPlay is supposed to work on Apple environments (I've seen it work several times on different iPhones).

Unfortunately for you, "doesn't work" doesn't give me much guidance.

Do you have more explicit information like :

- What is happening ? Are you trying to play a video?
- do you have an error notification?
- URL of your invidious instance
- if possible, the URL of your HoloPlay instance (this is not always possible)

Thank you 😃

**Comment by maboroshin** [comment]
The official instance works on iPhone iOS 17 or the old iOS 15: https://app.holoplay.io/

**Comment by Caobita9** [comment]
Hi,

I'm using the official instance now and it doesn't work either, the problem is that the music doesn't play, the interface loads correctly, but when I select a video/song, the player opens but doesn't play, I click pause and hit play again, it still doesn't play. No error appears.

Today, researching, I realized something, the only way I have managed to make it work is as follows:

- I select a song.
- In the player, I click on the option "Open video".
- I play the video and close it after 3-5 seconds.
- Automatically the song is played from the beginning through the player.

I am using iOS 17.4 on an iPhone 13 Pro Max.

Thanks.

**Comment by maboroshin** [comment]
@Caobita9 Information on the instances used is also requested.

**Comment by Caobita9** [comment]
As I said in the last comment, I am using the official instance [https://app.holoplay.io/](url)

If this is not what you need, I don't know what you mean, forgive my ignorance.

**Comment by maboroshin** [comment]
@Caobita9 You can check your Invidious instance from the settings.

**Comment by stephane-r** [comment]
> @Caobita9 You can check your Invidious instance from the settings.

Yes, like this 

![image](https://github.com/stephane-r/holoplay-pwa/assets/4712791/276a3c77-2528-46bd-a4d6-d932f054e129)

Also, can you share one of video you try to play ?

Thank you @Caobita9 💪

**Comment by Caobita9** [comment]
I am using the same instance as you, **invidious.fdn.fr** but I have tried others and they don't work neither.

I share some links of songs that I try to play:

[](https://app.holoplay.io/?v=AwSFuXm5wxg)
[](https://app.holoplay.io/?v=Mr6FX6azSAc)
[](https://app.holoplay.io/?v=wBUeg1Fed_o)

Thanks

**Comment by Caobita9** [comment]
I attach a video where you see that the player is not working and also showing what I said above, clicking on "Watch Video", playing it, stopping it, and it automatically starts the song in the player.

https://github.com/stephane-r/holoplay-pwa/assets/153455962/2aaaf505-7d74-4dfb-8f1f-392184640dcd

**Comment by stephane-r** [comment]
Thank you @Caobita9 :)

Mmmm, if the video player start automatically, this means that there is an error in the network request for the video.

I will see about adding a notification at this time in order to have a little more information on this usecase 👍 

Just for information, are you able to try on another device (mobile or desktop), on the same network ?

**Comment by Caobita9** [comment]
@stephane-r Yes, I can use it normally on my Windows 11 desktop computer, and also on another Ubuntu computer, all connected to the same network.

However, I don't think my network is the problem, I have tried using it from my iPhone with the mobile network and it doesn't work either.

It seems to be a problem with iOS, at least with the 17.4 beta version.

**Comment by Caobita9** [comment]
Hi @stephane-r @maboroshin 

Solved.

It seems it was a problem with version 17.4 beta, I have upgraded to version 17.4 beta 2 and now it works correctly.

Thanks for your help.

**Comment by stephane-r** [comment]
Very strange, good to know!

Thank you for your feedback and good listening 🎶 !
