### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by webmasterandy** [stephane-r/holoplay-pwa#90]
Docker says:

``` 
root@nas:/var/docker/holoplay# docker run -d -p 8006:8006 spout8301/holoplay:latest
Unable to find image 'spout8301/holoplay:latest' locally
docker: Error response from daemon: manifest for spout8301/holoplay:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

**Comment by stephane-r** [comment]
Hi,

Use the latest version code : spout8301/holoplay:1.12.1. You can see on Docker Hub : https://hub.docker.com/r/spout8301/holoplay/tags#!

**Comment by fuomag9** [comment]
> Hi,
> 
> Use the latest version code : spout8301/holoplay:1.12.1. You can see on Docker Hub : https://hub.docker.com/r/spout8301/holoplay/tags#!

You should tag the latest image with the latest version, so auto pulls can be done by stuff such as watchtower

**Comment by stephane-r** [comment]
You're right. I would make update on the Github Action to release both soon.

**Comment by stephane-r** [comment]
@fuomag9 #92
